// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * StartWatching — вызывается из фронтенда
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function StartWatching(path) {
    return $Call.ByID(4224750185, path);
}

/**
 * StopWatching — останавливает наблюдение
 * @returns {$CancellablePromise<void>}
 */
export function StopWatching() {
    return $Call.ByID(3766162357);
}
