// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close скрывает окно
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(32354819);
}

/**
 * Open показывает окно
 * @returns {$CancellablePromise<void>}
 */
export function Open() {
    return $Call.ByID(4195834921);
}
