// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Scanner - это структура, которая будет привязана к фронтенду Wails.
 * Она содержит методы для поиска путей к файлам игры.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckAndFindPaths - основная функция для поиска путей.
 * Эта функция будет привязана к фронтенду Wails.
 * @returns {$CancellablePromise<string[]>}
 */
export function CheckAndFindPaths() {
    return $Call.ByID(692361388).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * FindConfigOrExeParallel параллельно ищет пути к файлам config.lod.ini или war3.exe на всех логических дисках.
 * Эта функция привязана к фронтенду Wails.
 * @returns {$CancellablePromise<string[]>}
 */
export function FindConfigOrExeParallel() {
    return $Call.ByID(2040538117).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
